create table delivery(
	id integer primary key generated by default as identity,
	order_id integer not NULL,
	delivery_location text not NULL,
	date_order date not NULL,
	phone text not NULL,
	is_collected boolean default false,
	is_delivered boolean default false	
);
