create table Category (
	id integer primary key generated by default as identity,
	name text not NULL
);
insert into Category (name) values
('Бытовая техника'),
('Табак'),
('Электроника'),
('Продукты');

select * from Category;
