create table product (
	id integer primary key generated by default as identity,
	name text not NULL,
	count integer not NULL default 0,
	price double precision not NULL check (price > 0),
	brandId integer references brand(id),
	categoryId integer references category(id)
);

insert into product (name, count, price, brandId, categoryId) values
('Сок', 20, 15.11, 1, 4),
('Семечки', 50, 13.3, 5, 4),
('Юппи', 110, 6.57, 1, 4),
('Турбо', 1000, 1, 5, 4),
('Водка Распутин', 30, 30, 4, 4),
('Беламор', 70, 10, 2, 2),
('Стиральная машина', 4, 150, 1, 1),
('Детство', 1, 99999999, 5, 2);

select * from product;